version: "3.0"

services:

  logbook:
    environment:
      LOG_SIZE: 10485760
      NUM_SEGM: 2
    image: ahromis/logbook:latest
    volumes:
      - /var/run/log:/var/run/log
      - docker-journal:/var/log/docker
    deploy:
      mode: global

volumes:
  docker-journal:
    driver: local
