version: "3.0"

services:

  logbook:
    environment:
      LOG_SIZE: 10000000
      NUM_SEGM: 2
    image: ahromis/logbook:latest
    volumes:
      - /var/run/log:/var/run/log
      - docker-journal:/var/log/docker
    deploy:
      mode: global
      update_config:
         parallelism: 2
         delay: 10s
      restart_policy:
         condition: on-failure

volumes:
  docker-journal:
    driver: local
